[book]
authors = ["t22cs062"]
language = "ja"
multilingual = false
src = "./"
title = "社用車運行管理システム"

[build]
build-dir = "books"
create-missing = false

[output.html]
mathjax-support = true
preferred-dark-theme = "navy"

[output.html.print]
enable = true
